[build]
builder = "DOCKERFILE"
dockerfilePath = "FrontEnd/Dockerfile"

[deploy]
startCommand = "streamlit run frontend.py --server.port=$PORT --server.address=0.0.0.0 --server.headless=true"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10